apiVersion: v1
description: Helm Chart for Docker example-voting-app
name: example-voting-app
keywords:
- codefresh
- kubernetes
- example-voting-app
version: 0.1.1
sources:
- https://github.com/lrochette/example-voting-app
maintainers:
- name: Laurent Rochette
  email: laurent.rochette@codefresh.io
